apiVersion: v1
kind: Service
metadata: 
  name: aria-nginx
  namespace: kube-system
  annotations:
    aria.io/proxy-config: |
      listener: acc
      routes:
      - match: { prefix: "/ui/media/"}
        route: { prefix_rewrite: "/media/", timeout: normal }
spec:
  selector:
    app: aria-nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443