apiVersion: v1
kind: Service
metadata: 
  name: remote-indications
  namespace: billing
  annotations:
    aria.io/proxy-config: |
      listener: acc
      routes:
      - match: { prefix: "/ui/billing/remote-indications/"}
        route: { prefix_rewrite: "/", timeout: normal }
      - match: { prefix: "/ui/billing/remote-indications" }
        redirect: { path_redirect: "/ui/remote-indications/" }
spec:
  selector:
    app: remote-indications
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443