apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Name}}.api
  namespace: {{.Ns}}
  labels:
    aria-app: {{.Name}}.api
    tier: api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      aria-app: {{.Name}}.api
      tier: api
  template:
    metadata:
      labels:
        aria-app: {{.Name}}.api
        tier: api
    spec:
      containers:
      - name: {{.Name}}-api
        image: {{.Name}}.api.{{.Ns}}
        env:
        - { name: TZ, value: Europe/Chisinau }
        - { name: AUTH-TOKEN-KEY, valueFrom: { secretKeyRef: { name: auth-token-secret, key: auth-token-secret } } }
        ports:
        - containerPort: 443
        volumeMounts:
        - { name: certs, mountPath: /certs }
      volumes:
      - name: certs
        secret: { secretName: acc-certs }
      imagePullSecrets:
      - name: regcred
