apiVersion: v1
kind: Service
metadata: 
  name: {{.Name}}-api
  namespace: {{.Ns}}
  annotations:
    aria.io/proxy-config: |
      listener: {{.Listener}}
      default: false
      routes:
      - match: { prefix: "/api/{{.Ns}}/{{.Name}}/"}
        route: { prefix_rewrite: "/api/", timeout: long }
spec:
  selector:
    aria-app: {{.Name}}.api
    tier: api
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443