apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aria-proxy
  namespace: kube-system
  labels:
    app: aria-proxy
    kind: aria-service
spec:
  selector:
    matchLabels:
      app: aria-proxy
  template:
    metadata:
      labels:
        app: aria-proxy
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      terminationGracePeriodSeconds: 5
      containers:
      - name: aria-proxy-service
        image: 10.10.112.27:5000/aria-proxy-service:0.1.4
        ports:
        - { name: http, containerPort: 80, hostPort: 80 }
        - { name: acc-https, containerPort: 443, hostPort: 443 }
        - { name: io-https, containerPort: 8081, hostPort: 8081 }
        imagePullPolicy: IfNotPresent
        env:
        - { name: TZ, value: Europe/Chisinau }
        volumeMounts:
        - { name: certs, mountPath: /certs }
      - name: aria-proxy-manager
        image: 10.10.112.27:5000/aria-proxy-manager:0.1.4
        imagePullPolicy: IfNotPresent
      dnsPolicy: Default
      volumes:
      - name: certs
        secret: { secretName: acc-certs }
      serviceAccountName: aria-services-account
      imagePullSecrets:
      - name: regcred
