apiVersion: v1
kind: Namespace
metadata:
  name: aria
---
apiVersion: v1
kind: Namespace
metadata:
  name: billing
---
apiVersion: v1
kind: Namespace
metadata:
  name: finance
---
apiVersion: v1
kind: Namespace
metadata:
  name: utilities
