apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity.api
  namespace: admin
  labels:
    app: identity.api
    kind: aria-app
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity.api
  template:
    metadata:
      labels:
        app: identity.api
    spec:
      containers:
      - name: identity-api
        image: identity.api.admin
        ports:
        - containerPort: 443
        volumeMounts:
        - { name: certs, mountPath: /certs, readOnly: true }
      volumes:
      - name: certs
        hostPath: { path: /home/acc-server-admin/certs, readOnly: true }
      imagePullSecrets:
      - name: regcred
