apiVersion: v1
kind: Service
metadata: 
  name: identity-api
  namespace: admin
  annotations:
    aria.io/proxy-config: |
      listener: acc
      routes:
      - match: { prefix: "/api/identity/"}
        route: { prefix_rewrite: "/", timeout: normal }
spec:
  selector:
    app: identity.api
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443