apiVersion: v1
kind: Service
metadata: 
  name: nginx
  namespace: kube-system
  annotations:
    aria-proxy/config: |
      listener: main
      cluster:
        name: nginx-server
        connect_timeout: { seconds: 5 }
        soxket_address: { address: nginx-server, port_value: 443 }
      routes:
      - match: { prefix: "/ui/media/"}
        route: { prefix_rewrite: "/media/" }
      - match: { prefix: "/"}
        route: { prefix_rewrite: "/" }
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443