apiVersion: v1
kind: Service
metadata: 
  name: nginx
  namespace: kube-system
  annotations:
    aria.io/proxy-config: |
      listener: acc
      routes:
      - match: { prefix: "/ui/media/"}
        route: { prefix_rewrite: "/media/", timeout: normal }
      - match: { prefix: "/" }
        route: { prefix_rewrite: "/", timeout: long }
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443