apiVersion: v1
kind: Service
metadata: 
  name: quarkus-epayment-api
  namespace: billing
  annotations:
    aria.io/proxy-config: |
      listener: acc
      default: false
      routes:
      - match: { prefix: "/api/billing/quarkus-epayment/"}
        route: { prefix_rewrite: "/api/", timeout: long }
spec:
  selector:
    aria-app: quarkus-epayment.api
    tier: api
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443