apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: aria-publisher
  namespace: kube-system
  labels:
    app: aria-publisher
    kind: aria-service
spec:
  selector:
    matchLabels:
      app: aria-publisher
  template:
    metadata:
      labels:
        app: aria-publisher
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      terminationGracePeriodSeconds: 5
      containers:
      - name: aria-publisher
        image: 10.10.112.27:5000/aria-publisher:0.1.3
        ports:
        - { name: grpc, containerPort: 9999, hostPort: 9999 }
        imagePullPolicy: IfNotPresent
        env:
        - { name: TZ, value: Europe/Chisinau }
        volumeMounts:
        - { name: auth, mountPath: /auth, readOnly: true }
        - { name: certs, mountPath: /certs }
        - { name: docker-socket-volume, mountPath: /var/run/docker.sock }
        securityContext:
          privileged: true        
      dnsPolicy: Default
      volumes:
      - name: auth
        hostPath: { path: /home/acc-server-admin/auth, type: Directory }
      - name: certs
        secret: { secretName: acc-certs }
      - name: docker-socket-volume
        hostPath: { path: /var/run/docker.sock, type: File }
      serviceAccountName: aria-services-account
      imagePullSecrets:
      - name: regcred
