apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: admin
  labels:
    app: identity
    kind: aria-app
    tier: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      containers:
      - name: identity
        image: identity.ui.admin
        ports:
        - containerPort: 443
        volumeMounts:
        - { name: certs, mountPath: /certs, readOnly: true }
        - { name: nginx-conf, mountPath: /etc/nginx/conf.d }
      volumes:
      - name: certs
        hostPath: { path: /home/acc-server-admin/certs, readOnly: true }
      - name: nginx-conf
        configMap: { name: nginx-conf }
      imagePullSecrets:
      - name: regcred
