apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  namespace: admin
  labels:
    app: identity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
      spec:
        containers:
        - name: identity
          image: identity.ui.admin
          ports:
          - containerPort: 443
          volumeMounts:
          - { name: certs, mountPath: /certs, readOnly: true }
        volumes:
        - name: certs
          hostPath: { path: /home/acc-server-admin/certs, readOnly: true }
