apiVersion: v1
kind: Service
metadata: 
  name: identity
  namespace: admin
  annotations:
    aria.io/proxy-config: |
      listener: acc
      routes:
      - match: { prefix: "/ui/identity/"}
        route: { prefix_rewrite: "/", timeout: normal }
      - match: { prefix: "/ui/identity" }
        redirect: { path_redirect: "/ui/identity/" }
spec:
  selector:
    app: identity
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443