// Code generated by protoc-gen-go. DO NOT EDIT.
// source: publish-request.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DotnetOptions struct {
	FromClause           string   `protobuf:"bytes,1,opt,name=from_clause,json=fromClause,proto3" json:"from_clause,omitempty"`
	ProjectName          string   `protobuf:"bytes,2,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DotnetOptions) Reset()         { *m = DotnetOptions{} }
func (m *DotnetOptions) String() string { return proto.CompactTextString(m) }
func (*DotnetOptions) ProtoMessage()    {}
func (*DotnetOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_request_704f9050a4333cb7, []int{0}
}
func (m *DotnetOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DotnetOptions.Unmarshal(m, b)
}
func (m *DotnetOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DotnetOptions.Marshal(b, m, deterministic)
}
func (dst *DotnetOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DotnetOptions.Merge(dst, src)
}
func (m *DotnetOptions) XXX_Size() int {
	return xxx_messageInfo_DotnetOptions.Size(m)
}
func (m *DotnetOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DotnetOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DotnetOptions proto.InternalMessageInfo

func (m *DotnetOptions) GetFromClause() string {
	if m != nil {
		return m.FromClause
	}
	return ""
}

func (m *DotnetOptions) GetProjectName() string {
	if m != nil {
		return m.ProjectName
	}
	return ""
}

type JavaOptions struct {
	FromClause           string   `protobuf:"bytes,1,opt,name=from_clause,json=fromClause,proto3" json:"from_clause,omitempty"`
	JarfileName          string   `protobuf:"bytes,2,opt,name=jarfile_name,json=jarfileName,proto3" json:"jarfile_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JavaOptions) Reset()         { *m = JavaOptions{} }
func (m *JavaOptions) String() string { return proto.CompactTextString(m) }
func (*JavaOptions) ProtoMessage()    {}
func (*JavaOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_request_704f9050a4333cb7, []int{1}
}
func (m *JavaOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JavaOptions.Unmarshal(m, b)
}
func (m *JavaOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JavaOptions.Marshal(b, m, deterministic)
}
func (dst *JavaOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JavaOptions.Merge(dst, src)
}
func (m *JavaOptions) XXX_Size() int {
	return xxx_messageInfo_JavaOptions.Size(m)
}
func (m *JavaOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_JavaOptions.DiscardUnknown(m)
}

var xxx_messageInfo_JavaOptions proto.InternalMessageInfo

func (m *JavaOptions) GetFromClause() string {
	if m != nil {
		return m.FromClause
	}
	return ""
}

func (m *JavaOptions) GetJarfileName() string {
	if m != nil {
		return m.JarfileName
	}
	return ""
}

type WebUiOptions struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WebUiOptions) Reset()         { *m = WebUiOptions{} }
func (m *WebUiOptions) String() string { return proto.CompactTextString(m) }
func (*WebUiOptions) ProtoMessage()    {}
func (*WebUiOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_request_704f9050a4333cb7, []int{2}
}
func (m *WebUiOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebUiOptions.Unmarshal(m, b)
}
func (m *WebUiOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebUiOptions.Marshal(b, m, deterministic)
}
func (dst *WebUiOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebUiOptions.Merge(dst, src)
}
func (m *WebUiOptions) XXX_Size() int {
	return xxx_messageInfo_WebUiOptions.Size(m)
}
func (m *WebUiOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_WebUiOptions.DiscardUnknown(m)
}

var xxx_messageInfo_WebUiOptions proto.InternalMessageInfo

type CustomDockerfile struct {
	Dockerfile           []byte   `protobuf:"bytes,1,opt,name=dockerfile,proto3" json:"dockerfile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustomDockerfile) Reset()         { *m = CustomDockerfile{} }
func (m *CustomDockerfile) String() string { return proto.CompactTextString(m) }
func (*CustomDockerfile) ProtoMessage()    {}
func (*CustomDockerfile) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_request_704f9050a4333cb7, []int{3}
}
func (m *CustomDockerfile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustomDockerfile.Unmarshal(m, b)
}
func (m *CustomDockerfile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustomDockerfile.Marshal(b, m, deterministic)
}
func (dst *CustomDockerfile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustomDockerfile.Merge(dst, src)
}
func (m *CustomDockerfile) XXX_Size() int {
	return xxx_messageInfo_CustomDockerfile.Size(m)
}
func (m *CustomDockerfile) XXX_DiscardUnknown() {
	xxx_messageInfo_CustomDockerfile.DiscardUnknown(m)
}

var xxx_messageInfo_CustomDockerfile proto.InternalMessageInfo

func (m *CustomDockerfile) GetDockerfile() []byte {
	if m != nil {
		return m.Dockerfile
	}
	return nil
}

type Request struct {
	ArtifactName string `protobuf:"bytes,1,opt,name=artifact_name,json=artifactName,proto3" json:"artifact_name,omitempty"`
	Namespace    string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ArtifactKind string `protobuf:"bytes,3,opt,name=artifact_kind,json=artifactKind,proto3" json:"artifact_kind,omitempty"`
	ImageName    string `protobuf:"bytes,4,opt,name=image_name,json=imageName,proto3" json:"image_name,omitempty"`
	// Types that are valid to be assigned to DockerOptions:
	//	*Request_DotnetOptions
	//	*Request_JavaOptions
	//	*Request_WebuiOptions
	//	*Request_CustomDockerfile
	DockerOptions        isRequest_DockerOptions `protobuf_oneof:"docker_options"`
	DockerContent        []byte                  `protobuf:"bytes,9,opt,name=docker_content,json=dockerContent,proto3" json:"docker_content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_request_704f9050a4333cb7, []int{4}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetArtifactName() string {
	if m != nil {
		return m.ArtifactName
	}
	return ""
}

func (m *Request) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Request) GetArtifactKind() string {
	if m != nil {
		return m.ArtifactKind
	}
	return ""
}

func (m *Request) GetImageName() string {
	if m != nil {
		return m.ImageName
	}
	return ""
}

type isRequest_DockerOptions interface {
	isRequest_DockerOptions()
}

type Request_DotnetOptions struct {
	DotnetOptions *DotnetOptions `protobuf:"bytes,5,opt,name=dotnet_options,json=dotnetOptions,proto3,oneof"`
}

type Request_JavaOptions struct {
	JavaOptions *JavaOptions `protobuf:"bytes,6,opt,name=java_options,json=javaOptions,proto3,oneof"`
}

type Request_WebuiOptions struct {
	WebuiOptions *WebUiOptions `protobuf:"bytes,7,opt,name=webui_options,json=webuiOptions,proto3,oneof"`
}

type Request_CustomDockerfile struct {
	CustomDockerfile *CustomDockerfile `protobuf:"bytes,8,opt,name=custom_dockerfile,json=customDockerfile,proto3,oneof"`
}

func (*Request_DotnetOptions) isRequest_DockerOptions() {}

func (*Request_JavaOptions) isRequest_DockerOptions() {}

func (*Request_WebuiOptions) isRequest_DockerOptions() {}

func (*Request_CustomDockerfile) isRequest_DockerOptions() {}

func (m *Request) GetDockerOptions() isRequest_DockerOptions {
	if m != nil {
		return m.DockerOptions
	}
	return nil
}

func (m *Request) GetDotnetOptions() *DotnetOptions {
	if x, ok := m.GetDockerOptions().(*Request_DotnetOptions); ok {
		return x.DotnetOptions
	}
	return nil
}

func (m *Request) GetJavaOptions() *JavaOptions {
	if x, ok := m.GetDockerOptions().(*Request_JavaOptions); ok {
		return x.JavaOptions
	}
	return nil
}

func (m *Request) GetWebuiOptions() *WebUiOptions {
	if x, ok := m.GetDockerOptions().(*Request_WebuiOptions); ok {
		return x.WebuiOptions
	}
	return nil
}

func (m *Request) GetCustomDockerfile() *CustomDockerfile {
	if x, ok := m.GetDockerOptions().(*Request_CustomDockerfile); ok {
		return x.CustomDockerfile
	}
	return nil
}

func (m *Request) GetDockerContent() []byte {
	if m != nil {
		return m.DockerContent
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Request) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Request_OneofMarshaler, _Request_OneofUnmarshaler, _Request_OneofSizer, []interface{}{
		(*Request_DotnetOptions)(nil),
		(*Request_JavaOptions)(nil),
		(*Request_WebuiOptions)(nil),
		(*Request_CustomDockerfile)(nil),
	}
}

func _Request_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Request)
	// docker_options
	switch x := m.DockerOptions.(type) {
	case *Request_DotnetOptions:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DotnetOptions); err != nil {
			return err
		}
	case *Request_JavaOptions:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.JavaOptions); err != nil {
			return err
		}
	case *Request_WebuiOptions:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.WebuiOptions); err != nil {
			return err
		}
	case *Request_CustomDockerfile:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.CustomDockerfile); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Request.DockerOptions has unexpected type %T", x)
	}
	return nil
}

func _Request_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Request)
	switch tag {
	case 5: // docker_options.dotnet_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DotnetOptions)
		err := b.DecodeMessage(msg)
		m.DockerOptions = &Request_DotnetOptions{msg}
		return true, err
	case 6: // docker_options.java_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JavaOptions)
		err := b.DecodeMessage(msg)
		m.DockerOptions = &Request_JavaOptions{msg}
		return true, err
	case 7: // docker_options.webui_options
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(WebUiOptions)
		err := b.DecodeMessage(msg)
		m.DockerOptions = &Request_WebuiOptions{msg}
		return true, err
	case 8: // docker_options.custom_dockerfile
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(CustomDockerfile)
		err := b.DecodeMessage(msg)
		m.DockerOptions = &Request_CustomDockerfile{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Request_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Request)
	// docker_options
	switch x := m.DockerOptions.(type) {
	case *Request_DotnetOptions:
		s := proto.Size(x.DotnetOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_JavaOptions:
		s := proto.Size(x.JavaOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_WebuiOptions:
		s := proto.Size(x.WebuiOptions)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Request_CustomDockerfile:
		s := proto.Size(x.CustomDockerfile)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Response struct {
	// Types that are valid to be assigned to ResponseVariants:
	//	*Response_ImageVersion
	//	*Response_ErrorDescription
	ResponseVariants     isResponse_ResponseVariants `protobuf_oneof:"response_variants"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_publish_request_704f9050a4333cb7, []int{5}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_ResponseVariants interface {
	isResponse_ResponseVariants()
}

type Response_ImageVersion struct {
	ImageVersion string `protobuf:"bytes,1,opt,name=image_version,json=imageVersion,proto3,oneof"`
}

type Response_ErrorDescription struct {
	ErrorDescription string `protobuf:"bytes,2,opt,name=error_description,json=errorDescription,proto3,oneof"`
}

func (*Response_ImageVersion) isResponse_ResponseVariants() {}

func (*Response_ErrorDescription) isResponse_ResponseVariants() {}

func (m *Response) GetResponseVariants() isResponse_ResponseVariants {
	if m != nil {
		return m.ResponseVariants
	}
	return nil
}

func (m *Response) GetImageVersion() string {
	if x, ok := m.GetResponseVariants().(*Response_ImageVersion); ok {
		return x.ImageVersion
	}
	return ""
}

func (m *Response) GetErrorDescription() string {
	if x, ok := m.GetResponseVariants().(*Response_ErrorDescription); ok {
		return x.ErrorDescription
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Response) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Response_OneofMarshaler, _Response_OneofUnmarshaler, _Response_OneofSizer, []interface{}{
		(*Response_ImageVersion)(nil),
		(*Response_ErrorDescription)(nil),
	}
}

func _Response_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Response)
	// response_variants
	switch x := m.ResponseVariants.(type) {
	case *Response_ImageVersion:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ImageVersion)
	case *Response_ErrorDescription:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.ErrorDescription)
	case nil:
	default:
		return fmt.Errorf("Response.ResponseVariants has unexpected type %T", x)
	}
	return nil
}

func _Response_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Response)
	switch tag {
	case 1: // response_variants.image_version
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ResponseVariants = &Response_ImageVersion{x}
		return true, err
	case 2: // response_variants.error_description
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.ResponseVariants = &Response_ErrorDescription{x}
		return true, err
	default:
		return false, nil
	}
}

func _Response_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Response)
	// response_variants
	switch x := m.ResponseVariants.(type) {
	case *Response_ImageVersion:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ImageVersion)))
		n += len(x.ImageVersion)
	case *Response_ErrorDescription:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.ErrorDescription)))
		n += len(x.ErrorDescription)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*DotnetOptions)(nil), "api.DotnetOptions")
	proto.RegisterType((*JavaOptions)(nil), "api.JavaOptions")
	proto.RegisterType((*WebUiOptions)(nil), "api.WebUiOptions")
	proto.RegisterType((*CustomDockerfile)(nil), "api.CustomDockerfile")
	proto.RegisterType((*Request)(nil), "api.Request")
	proto.RegisterType((*Response)(nil), "api.Response")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PublishRequestClient is the client API for PublishRequest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublishRequestClient interface {
	Publish(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type publishRequestClient struct {
	cc *grpc.ClientConn
}

func NewPublishRequestClient(cc *grpc.ClientConn) PublishRequestClient {
	return &publishRequestClient{cc}
}

func (c *publishRequestClient) Publish(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/api.PublishRequest/Publish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublishRequestServer is the server API for PublishRequest service.
type PublishRequestServer interface {
	Publish(context.Context, *Request) (*Response, error)
}

func RegisterPublishRequestServer(s *grpc.Server, srv PublishRequestServer) {
	s.RegisterService(&_PublishRequest_serviceDesc, srv)
}

func _PublishRequest_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublishRequestServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.PublishRequest/Publish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublishRequestServer).Publish(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _PublishRequest_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.PublishRequest",
	HandlerType: (*PublishRequestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Publish",
			Handler:    _PublishRequest_Publish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publish-request.proto",
}

func init() {
	proto.RegisterFile("publish-request.proto", fileDescriptor_publish_request_704f9050a4333cb7)
}

var fileDescriptor_publish_request_704f9050a4333cb7 = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x4d, 0x29, 0x6c, 0xb7, 0xd3, 0xa4, 0x6a, 0x8d, 0x56, 0x8a, 0x10, 0x1f, 0x4b, 0x10, 0x52,
	0x2f, 0xdb, 0x43, 0x11, 0x12, 0x82, 0xdb, 0xb6, 0x87, 0x0a, 0x24, 0x3e, 0x82, 0x80, 0x63, 0xe4,
	0x26, 0x2e, 0x78, 0xb7, 0xb1, 0x8d, 0xed, 0x94, 0x5f, 0xc7, 0x7f, 0x43, 0x1e, 0x3b, 0x6d, 0xb3,
	0x37, 0x8e, 0x7e, 0x33, 0xef, 0xcd, 0xcc, 0x7b, 0x09, 0x5c, 0xa8, 0x66, 0xb3, 0xe3, 0xe6, 0xd7,
	0x95, 0x66, 0xbf, 0x1b, 0x66, 0xec, 0x5c, 0x69, 0x69, 0x25, 0xe9, 0x53, 0xc5, 0xb3, 0xaf, 0x90,
	0xac, 0xa4, 0x15, 0xcc, 0x7e, 0x52, 0x96, 0x4b, 0x61, 0xc8, 0x33, 0x18, 0x6d, 0xb5, 0xac, 0x8b,
	0x72, 0x47, 0x1b, 0xc3, 0xd2, 0xde, 0x65, 0x6f, 0x36, 0xcc, 0xc1, 0x41, 0x4b, 0x44, 0xc8, 0x73,
	0x88, 0x95, 0x96, 0x37, 0xac, 0xb4, 0x85, 0xa0, 0x35, 0x4b, 0xef, 0x61, 0xc7, 0x28, 0x60, 0x1f,
	0x69, 0xcd, 0xb2, 0x2f, 0x30, 0x7a, 0x4f, 0xf7, 0xf4, 0x7f, 0x24, 0x6f, 0xa8, 0xde, 0xf2, 0x1d,
	0xeb, 0x48, 0x06, 0x0c, 0x25, 0xc7, 0x10, 0xff, 0x60, 0x9b, 0x6f, 0x3c, 0x68, 0x66, 0x0b, 0x98,
	0x2c, 0x1b, 0x63, 0x65, 0xbd, 0x92, 0xe5, 0x2d, 0xc3, 0x3e, 0xf2, 0x14, 0xa0, 0x3a, 0xbc, 0x70,
	0x4c, 0x9c, 0x9f, 0x20, 0xd9, 0xdf, 0x3e, 0x0c, 0x72, 0x6f, 0x01, 0x79, 0x01, 0x09, 0xd5, 0x96,
	0x6f, 0x69, 0x7b, 0x86, 0xdf, 0x2a, 0x6e, 0x41, 0x37, 0x94, 0x3c, 0x86, 0xa1, 0xab, 0x19, 0x45,
	0xcb, 0x76, 0xa9, 0x23, 0xd0, 0x91, 0xb8, 0xe5, 0xa2, 0x4a, 0xfb, 0x5d, 0x89, 0x0f, 0x5c, 0x54,
	0xe4, 0x09, 0x00, 0xaf, 0xe9, 0xcf, 0x70, 0xd8, 0x7d, 0xaf, 0x81, 0x08, 0x4e, 0x78, 0x07, 0xe3,
	0x0a, 0xed, 0x2f, 0xa4, 0x3f, 0x2c, 0x7d, 0x70, 0xd9, 0x9b, 0x8d, 0x16, 0x64, 0x4e, 0x15, 0x9f,
	0x77, 0x92, 0x59, 0x47, 0x79, 0x52, 0x75, 0xa2, 0x7a, 0xed, 0x6c, 0xdb, 0xd3, 0x03, 0xf5, 0x0c,
	0xa9, 0x13, 0xa4, 0x9e, 0xf8, 0xbf, 0x8e, 0x9c, 0x95, 0xc7, 0x38, 0xde, 0x40, 0xf2, 0x87, 0x6d,
	0x1a, 0x7e, 0xe0, 0x0d, 0x90, 0x37, 0x45, 0xde, 0xa9, 0xc9, 0xeb, 0x28, 0x8f, 0xb1, 0xb3, 0x65,
	0xae, 0x60, 0x5a, 0xa2, 0xe9, 0xc5, 0x89, 0xcf, 0xe7, 0xc8, 0xbe, 0x40, 0xf6, 0xdd, 0x48, 0xd6,
	0x51, 0x3e, 0x29, 0xef, 0xc6, 0xf4, 0xd2, 0xdd, 0xec, 0x5e, 0x45, 0x29, 0x85, 0x65, 0xc2, 0xa6,
	0x43, 0x8c, 0x2a, 0xf1, 0xe8, 0xd2, 0x83, 0xd7, 0x93, 0x43, 0x5b, 0xd8, 0x33, 0x6b, 0xe0, 0x3c,
	0x67, 0x46, 0x49, 0x61, 0x9c, 0x48, 0xe2, 0x7d, 0xdd, 0x33, 0x6d, 0xb8, 0x14, 0x3e, 0x3f, 0xb7,
	0x31, 0xc2, 0xdf, 0x3d, 0x4a, 0xae, 0x60, 0xca, 0xb4, 0x96, 0xba, 0xa8, 0x98, 0x29, 0x35, 0x47,
	0x21, 0x9f, 0xa4, 0x5b, 0x0d, 0x4b, 0xab, 0x63, 0xe5, 0xfa, 0x21, 0x4c, 0x75, 0x98, 0x50, 0xec,
	0xa9, 0xe6, 0x54, 0x58, 0xb3, 0x78, 0x0b, 0xe3, 0xcf, 0xfe, 0x07, 0x6a, 0x3f, 0x9e, 0x19, 0x0c,
	0x02, 0x42, 0x62, 0xbc, 0x3b, 0x14, 0x1e, 0x25, 0xe1, 0xe5, 0x25, 0xb2, 0x68, 0x73, 0x86, 0xbf,
	0xda, 0xab, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x63, 0x96, 0xfd, 0x83, 0x03, 0x00, 0x00,
}
