apiVersion: v1
kind: Service
metadata: 
  name: android-routes-api
  namespace: billing
  annotations:
    aria.io/proxy-config: |
      listener: acc
      routes:
      - match: { prefix: "/api/android-routes/"}
        route: { prefix_rewrite: "/api/", timeout: normal }
spec:
  selector:
    app: android-routes.api
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443