apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: image-builder
  namespace: aria
  labels:
    app: image-builder
spec:
  selector:
    matchLabels:
      app: image-builder
  template:
    metadata:
      labels:
        app: image-builder
      spec:
        nodeSelector:
            node-role.kubernetes.io/master: ""
        tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
        terminationGracePeriodSeconds: 5
        containers:
        - name: image-builder
          image: 127.0.0.1:32000/image-builder.aria:0.0.1
          imagePullPolicy: ifNotPresent
          ports:
          - containerPort: 443
          env:
          - { name: TZ, value: Europe/Chisinau }
