apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-intersystems
  namespace: utilities
  labels:
    app: transfer-intersystems
    kind: aria-app
    tier: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: transfer-intersystems
  template:
    metadata:
      labels:
        app: transfer-intersystems
    spec:
      containers:
      - name: transfer-intersystems
        image: transfer-intersystems.ui.utilities
        ports:
        - containerPort: 443
        volumeMounts:
        - { name: certs, mountPath: /certs }
        - { name: nginx-conf, mountPath: /etc/nginx/conf.d }
      volumes:
      - name: certs
        secret: { secretName: acc-certs }
      - name: nginx-conf
        configMap: { name: nginx-conf }
      imagePullSecrets:
      - name: regcred
